### PR TITLE
Add Download section

### PR DESCRIPTION
**Pull request by JoshAtticus**

### CODE REVIEW

**Comment by Mwalters75** [comment]
Maybe you can add a curl command for the link, like `curl https://github.com/Melt2002/MeltOS/raw/main/main.py`?

**Comment by Melt2002** [comment]
I don't feel this is necessary, as you can easily download using GitHub's "Code" button (attachment 1) or the releases page (attachment 2)
image
image

**Comment by Melt2002** [comment]
> Maybe you can add a curl command for the link, like `curl https://github.com/Melt2002/MeltOS/raw/main/main.py`?

That would just spit the contents of main.py out in the terminal, not download it.

**Comment by JoshAtticus** [comment]
> I don't feel this is necessary, as you can easily download using GitHub's "Code" button (attachment 1) or the releases page (attachment 2) image image

But that includes everything including things like readme, and you have to manually extract it. As you only need the main script, adding a download button, OR creating a release with the main script is more convenient.

**Comment by Melt2002** [comment]
> > I don't feel this is necessary, as you can easily download using GitHub's "Code" button (attachment 1) or the releases page (attachment 2) image image
> 
> But that includes everything including things like readme, and you have to manually extract it. As you only need the main script, adding a download button, OR creating a release with the main script is more convenient.

Each copy of MeltOS should come with the main.py and LICENSE files at a minimum.

**Comment by JoshAtticus** [comment]
> > > I don't feel this is necessary, as you can easily download using GitHub's "Code" button (attachment 1) or the releases page (attachment 2) image image
> > 
> > 
> > But that includes everything including things like readme, and you have to manually extract it. As you only need the main script, adding a download button, OR creating a release with the main script is more convenient.
> 
> Each copy of MeltOS should come with the main.py and LICENSE files at a minimum.

Done, there is now a download button that downloads the main.py file and LICENSE file in a zip. I know you could do the same with the code section, but this button is for <b>convenience</b>.

**Comment by Melt2002** [comment]
> > [snip]
> Done, there is now a download button that downloads the main.py file and LICENSE file in a zip. I know you could do the same with the code section, but this button is for convenience, as most people will look for a download button in the readme or file in the releases section.

I haven't seen anyone complaining about this until now. Without more people's opinions, this isn't being merged.

**Comment by JoshAtticus** [comment]
> > > [snip]
> > 
> > 
> > Done, there is now a download button that downloads the main.py file and LICENSE file in a zip. I know you could do the same with the code section, but this button is for convenience, as most people will look for a download button in the readme or file in the releases section.
> 
> I haven't seen anyone complaining about this until now. Without more people's opinions, this isn't being merged.

Ok, you do you

**Pull request closed without merging**
